#
# Reads the value of a secret
#
# Input variables:
#   service_directory   Directory of the service
#   secret_name         Secret file name
#   create_if_missing   If True, {{ value_if_missing }} will be saved to file
#   output_var          Name of the variable into which the secret will be saved
#

- name: Create secrets directory
  become: true
  file:
    path: "{{ service_directory }}/.secrets"
    state: directory
    mode: '0700'


- name: Check if secret exists
  become: true
  stat:
    path: "{{ service_directory }}/.secrets/{{ secret_name }}"
  register: secret_file

- name: Generate secret
  when: not secret_file.stat.exists and create_if_missing
  become: true
  copy:
    dest: "{{ service_directory }}/.secrets/{{ secret_name }}"
    content: "{{ lookup('ansible.builtin.password', '/dev/null chars=ascii_letters,digits length=40') }}"


- name: Read secret
  when: secret_file.stat.exists or create_if_missing
  become: true
  block:
    - slurp:
        src: "{{ service_directory }}/.secrets/{{ secret_name }}"
      register: secret_slurp
    - set_fact:
        "{{ output_var }}": "{{ secret_slurp.content | b64decode }}"

- name: Read empty secret
  when: (not secret_file.stat.exists) and (not create_if_missing)
  set_fact:
    "{{ output_var }}": ""
