- name: Stopping Taiga
  become: true
  ignore_errors: true
  community.docker.docker_compose_v2:
    project_src: "{{ taiga_directory }}"
    state: absent

- name: Delete nginx conf
  ansible.builtin.import_tasks:
    file: utilities/delete_nginx_conf.yml
  vars:
    label: "taiga"

- name: Remove backup cron job
  become: true
  ansible.builtin.cron:
    name: "Taiga backup"
    state: absent
